version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: redmine
  redmine:
    image: redmine:latest
    restart: always
    networks:
      - redmine
    volumes:
      - ./redmine_files:/usr/src/redmine/files
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: user
      REDMINE_DB_PASSWORD: userpassword

volumes:
  postgres-data:
networks:
  redmine:
    driver: bridge
